<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Employee_Offboarding.Application\Employee_Offboarding.Application.csproj" />
    <ProjectReference Include="..\Employee_Offboarding.Domain\Employee_Offboarding.Domain.csproj" />
  </ItemGroup>

</Project>
